mirrorlist/apache/mirrorlist-server.conf
Fixes https://fedorahosted.org/mirrormanager/ticket/52
=> Update paths to the wsgi files in the apache configuration files for mirrorlist

fedmsg.d/example-config.py, mirrormanager2/app.py
@ralphbean @pypingou Messages are sent on fedmsg when a mirror is added and when a mirror is updated as discussed in issue fedora-infra/fedmsg#245 . Please review. Thankyou :)
=> Added fedmsg messages to mirrormanager2

mirrormanager2/templates/fedora/host.html
Simple fix to link to the correct crawler log file.
=> Fix link to the crawler log file

alembic.ini, alembic/env.py, alembic/script.py.mako, alembic/versions/24681dabe5fa_add_host_columns.py, mirrormanager2/lib/model.py
If MM2 should go productive soon I would like to add additional fields to the database so that additional crawler features do not need changes to the database.
=> Additional columns

utility/mm2_crawler
The list of all categories was added instead of each category separately.
=> Fix category crawling

utility/mm2_last-sync
last-sync is a script to query the Fedora message bus if one or all
repositories need an update.
http://fedoraproject.org/wiki/Infrastructure/Mirroring#Mirror_Frequency
https://fedorahosted.org/fedora-infrastructure/ticket/4539
=> Added last-sync script as mm2_last-sync

utility/mirrormanager2.spec
reference: https://fedoraproject.org/wiki/Packaging:ScriptletSnippets#Systemd
=> Adjust the spec file to the systemd packaging guidelines for Fedora

mirrormanager2/app.py, mirrormanager2/templates/fedora/host.html
Only the admins can add/remove them and do not check authorization twice when not needed
=> Fix peer ASNs

mirrormanager2/templates/fedora/master.html, mirrormanager2/templates/fedora/master_noauth.html, mirrormanager2/templates/fedora/mirrors.html
This makes it possible to make publiclist varnish cached
because that doesn't depend on any cookie status anymore.
=> Create noauthed master for mirror publiclist

client/report_mirror
Fixes https://bugzilla.redhat.com/1162275
=> The program uses "import xmlrpclib" so refer to the module namespace explicitly

utility/mm2_umdl.logrotate
=> Adjust the logrotate configuration to fix the permission denied error

mirrormanager2/api.py
This endpoint can be used to check the status of mirrormanager's UI
Fixes https://github.com/fedora-infra/mirrormanager2/issues/83
=> Add a new API endpoint listing the repositories

mirrormanager2/app.py, mirrormanager2/templates/fedora/host_category.html, mirrormanager2/templates/fedora/host_category_new.html
Fixes https://github.com/fedora-infra/mirrormanager2/issues/97
=> Only MM2 admins are allowed to change the always_up2date flag of a mirror

utility/mm2_update-single-file-detail
This is a script we might try and use to speed up recovery of the pkl data.
=> First pass at update-single-file-detail

utility/mirrormanager2.spec, utility/mm2_crawler, utility/mm2_update-master-directory-list
This PR contains three smaller changes:
* Bring some changes from @pypingou's umdl2 branch to the current umdl to correctly handle version and repository creation.
* Handle continents which are not specified in upper case.
* Add python-GeoIP as a RPM dependency to the crawler sub-package.
=> Different small umdl and crawler fixes

utility/mm2_update-master-directory-list
=> Use common umdl code provided by mirrormanager2/lib/umdl.py

mirrormanager2/app.py
Fixes https://github.com/fedora-infra/mirrormanager2/issues/125
=> Remove trailing slash of site and host_category_url

mirrormanager2/app.py
Fixes https://github.com/fedora-infra/mirrormanager2/issues/128
=> Ensure that new host and new site are admin_active

mirrormanager2/forms.py, mirrormanager2/templates/fedora/host.html, mirrormanager2/templates/fedora/host_new.html, mirrormanager2/templates/fedora/site_new.html
fixes https://github.com/fedora-infra/mirrormanager2/issues/142
=> Improved documentation and validation

mirrorlist/mirrorlist_server.py
=> setup_continents wants to use info we just loaded from the pkl

utility/mm2_propagation
This is easier to immediately identify as wrong vs good
=> Make green be synced and red be older

mirrormanager2/lib/model.py, utility/mm2_emergency-expire-repo
=> Add function to emergency clear all old files from a repo

mirrormanager2/lib/repomap.py
=> Adjust repomap for the new repo layout

mirrormanager2/lib/hostconfig.py, mirrormanager2/xmlrpc.py
This should help with finding issues with checkin.
=> Add logging to checkin code

mirrormanager2/templates/fedora/admin/admin_master.html, mirrormanager2/templates/fedora/master_noauth.html, utility/mm2_generate-worldmap
This avoids potential security risk:
- https://dev.to/ben/the-targetblank-vulnerability-by-example
- https://mathiasbynens.github.io/rel-noopener/
=> Specify rel="noopener noreferrer" to link including target='_blank'

utility/mm2_update-master-directory-list
The following commits are fixing a few minor bugs which have been detected once the 0.8 release has been deployed on Fedora's production systems. Once this has been merged I am planing to release it as 0.8.1.
=> Simple fixes since last release

utility/mm2_move-devel-to-release
=> move-devel-to-release: fix the script to work with f26

mirrormanager2/lib/repomap.py
=> repomap: add a version suffix to the modular repositories

mirrormanager2/app.py, tests/__init__.py, tests/test_ui_app.py
=> Toggle private

.travis.yml, Vagrantfile.example, ansible.cfg, devel/ansible/playbook.yml, devel/ansible/roles/core/tasks/main.yml, devel/ansible/roles/dev/tasks/main.yml, requirements.txt
=> Update the MirrorManager Vagrant box to F-32 and various fixes.

.github/workflows/ci.yml, alembic/versions/920e847c8c36_add_admin_only_category.py, mirrormanager2/app.py, mirrormanager2/lib/__init__.py, mirrormanager2/lib/model.py, tests/__init__.py, tests/test_mmlib.py, tests/test_ui_admin.py, tests/test_ui_app.py, tests/test_umdl.py, utility/mirrormanager2.spec
=> Support admin only categories

doc/contributors.rst, mirrormanager2/__init__.py, utility/mirrormanager2.spec, utility/mm2_crawler
Add support for empty top directories.
=> empty topdir

.gitignore, README.rst, Vagrantfile, devel/ansible/roles/dev/files/mirrormanager2.cfg, devel/ansible/roles/dev/files/mirrormanager2.service, devel/ansible/roles/dev/tasks/main.yml, mirrormanager2/app.py, mirrormanager2/default_config.py, requirements.txt, runtests.sh, tests/__init__.py, tests/client_secrets.json, tests/mirrormanager2.cfg, tests/test_ui_app.py, utility/mirrormanager2.spec
Update the vagrant setup, andconvert from openid to OIDC
=> add OIDC support

mirrormanager2/crawler/connector.py, mirrormanager2/crawler/rsync_connector.py
This fixes the crawler incorrectly marking directories as out of date.
=> Fix crawler

.pre-commit-config.yaml, doc/database_schema.md, mirrormanager2/lib/migrations/versions/3264c6353b51_indexes.py, mirrormanager2/lib/model.py
This changeset adds some indexes on queries that are in `mirrormanager2/lib/__init__.py`.
Fixes: #473
=> Add indexes
