- utility/mm2_crawler
If any of the active fields is not set the host is disabled;
Not the other way around.
> Fix host selection logic in the crawler.

- mirrormanager2/lib/sync.py
- utility/mm2_crawler
- utility/mm2_update-master-directory-list
For better problem analysis it is helpful to know
which rsync command is actually used by MirrorManager.
> Print out the rsync command (including parameters)

- mirrormanager2/default_config.py
- utility/mirrormanager2.cfg.sample
- utility/mm2_crawler
Until now the command-line options of the rsync command to
crawl rsync mirrors has been hardcoded. This gives the option
to influence those those command-line options from the
configuration file.
> Add the possibility to influence rsync crawler

- mirrormanager2/default_config.py
- utility/mirrormanager2.cfg.sample
- utility/mirrormanager2.spec
- utility/mm2_crawler
- utility/mm2_crawler.logrotate
MM1 used to log for each crawler the output under <hostid>.log.
This adds the per host logging to the new thread based design.
These log files are referenced on each host page in the web
interface.
> Enable per crawler thread logging

- mirrorlist/systemd/mirrormanager_tempfile.conf
- utility/mirrormanager2.spec
To be able to not run the cronjobs as root but as the
user 'mirrormanager' this user is now created for the
mirrorlist, backend and crawler sub-package. The required
directories are now also owned by mirrormanager:mirrormanager.
> Do not run cronjobs as root

- utility/mm2_crawler
The update of the field last_crawled was not working due to the
wrong name (lastCrawled).
The field last_crawl_duration was not updated at all as it used
to be written by the master process doing the forking (before using
threads).
Only the changes to the threaded DB session where commit()ted and
close()d but the ones to the global session. To update crawl time
and duration the global DB session is now also commit()ted and
close()d.
> Update the last_crawled and last_crawled_duration correctly.

- utility/mm2_crawler
If the crawler was running for some time the per thread
file logging would start to log to multiple files. Now,
with the removal and closing of the FileHandler the
logging works as it is expected to.
> Close per thread logging correctly.

- utility/mm2_crawler
Add information about the number of active threads and
how many hosts still need to be crawled to the crawler
logging output.
> Add more informations to the log output.

- mirrormanager2/lib/__init__.py
- utility/mm2_crawler
MM1 used to sort the hosts to be crawled by the duration
of the last crawl (descending). Add this functionality to MM2.
> Start crawling the hosts which require the most time.

- utility/mm2_crawler
As the functionality is already there only select the hosts
from the database which will actually be used later. By not
selecting anyway unwanted hosts the memory usage should be
also slightly decreased.
> Let the database to the work

- utility/mm2_crawler
* Initialize the stats dict correctly.
* Store the time of the last crawl also if the crawl fails.
* Commit the database changes also if an error occured.
> This commit combines a few simple changes.

- utility/mirrormanager2.spec
This will bring the definition of the RPM macros used in %files:
%{_tmpfilesdir}/ and %{_unitdir}/
> Ask to build with systemd-devel to simplify

- utility/mm2_crawler
mm2_crawler crashes intermittently  in curl:
https://bugzilla.redhat.com/show_bug.cgi?id=1204825
it seems to be related to urlgrabber in threaded application. As
urlgrabber is only used once to download files to calculate the
checksum it is easy to replace this simple download with urllib2.
> Use urllib2 instead of urlgrabber

- utility/mm2_crawler
If the given timeout for the crawling of a host has been reached
has not been checked at enough places. Now the crawler actually
aborts if a host has not been crawled in the given time.
The timeout_check() function no longer gets the complete options
data structure but only the timeout and a few additional comments
have been added to the code.
Previously the crawler marked a host as not up to date if a single
category on that host has time out. This functionality is still the
same but now explicitly mentioned in the comments.
> Fix crawler timeout

- utility/mm2_crawler
Very simple one line fix to close temporary files created by run_rsync()
> run_rsync() returns a temporary file which needs to be closed

- mirrorlist/apache/mirrorlist-server.conf
For every alias, you need to have either a Directory or a Location
that matches it.
Source: https://wiki.apache.org/httpd/ClientDeniedByServerConfiguration
> Add a Location tag for static

- utility/mm2_crawler
The crawler was still crashing sometimes in libpython2.7.so.1.0.
This seems to be related to sqlalchemy and its usage combined with
threads. There was one DB session open in the main thread and for
each worker thread another DB session was opened. This was tracked
at https://fedorahosted.org/mirrormanager/ticket/57
This lead to
python[1156]: segfault at 58 ip 00007fe6fefd59f7 sp 00007fe68a7fa750 error 4 in libpython2.7.so.1.0[7fe6feef9000+178000]
and on the console mm2_crawler was complaining about:
/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py:1919: SAWarning: Attribute history events accumulated on 125 previously clean instances within inner-flush event handlers have been reset, and will not result in database updates. Consider using set_committed_value() within …
> Remove another potential segfault

- mirrormanager2/lib/model.py
- utility/mm2_crawler
Now that there are more checks if a timeout has occurred it was
observed that the function set_not_up2date() takes enormous amounts
of time to finish. The function is looping over each directory in
a category and marking it as not up to date. Unfortunately there
was a session.commit() after each directory update which required
huge amounts of time. Now all directories are marked as not up to
date and then a single session.commit() is executed.
This is still a bit strange as all other DB accesses and changes
are only committed at the end of a crawler thread and not somewhere
in a function which is outside of the crawler.
> Decrease time required for set_not_up2date()

- mirrormanager2/default_config.py
- mirrormanager2/forms.py
- mirrormanager2/templates/fedora/host.html
- utility/mirrormanager2.cfg.sample
- utility/mm2_crawler
Mirrors which have failed to be successfully crawled for a certain
number of crawls are now automatically disabled (user_active).
The reason for the automatic disabling is visible in the field
disable_reason.
> Add support to auto disable mirrors

- utility/mm2_crawler
There are a few hosts in the DB which do not have the configured URL
anymore. Auto disable the hosts if the broken URL persists for a
certain number of crawls. Before any other access to the host a
connection is made if either via http or ftp the host can be reached.
> Auto disable hosts which have a URL configured but which does not exist

- utility/mm2_crawler
Only update crawl_duration at the end of crawl of a host
and not after each category. As it is a host specific property
it only makes sense to update it once.
> crawl_duration is a host specific property

- utility/mm2_crawler
lighttpd returns a Content-Length for directories.
apache and nginx do not.
For the basic check in check_for_base_dir() it is only
relevant if the directory exists or not. Therefore
passing None as filedata[]. This needs to be handled.
> Handle lighttpd returing a content length for directories

- utility/mm2_crawler
The crawler was only looking at the files which a mirror actually
had and not at the files it is supposed to have. This lead to the
situation that a newly added host or category was never crawled
successfully. Now the crawler checks the list of files which are
supposed to be on the host and compares it with the actual content
of the crawled mirror.
> Scan the directories which are supposed to be on each mirror.

- mirrormanager2/default_config.py
- utility/mirrormanager2.cfg.sample
- utility/mirrormanager2.spec
- utility/mm2_crawler
- utility/mm2_umdl.logrotate
- utility/mm2_update-master-directory-list
These two commits try to fix logging to umdl.log and where that file should be and also introduces the possibility to only scan a single category. This opens up the possibility to start a category specific scan upon fedmsg notifications and not run a scan over the whole tree every two hours.
> Umdl log and category fixes

- utility/mm2_crawler
The crawler requires a lot of memory. With the explicit garbage
collection at the end of each crawler thread the crawler has not
been OOM killed for the last 4 runs. If this actually helps is
not very clear but it seems to slightly decrease the OOM killed
frequency. Unfortunately it seems difficult to tell which part
of the crawler and which thread is using the memory and for what.
> [RFC] Trying explicit garbage collection

- utility/mm2_crawler
The timeout check was only used between the HTTP/FTP connections.
It could still happen that the crawler was waiting for a very long
time on a single open connection. Specify the timeout now also for
each opened HTTP/FTP connection to make sure the crawler times out
after the specified time.
> Use defined timeout also for HTTP/FTP connections.

- utility/backend_tempfile.conf
- utility/mirrormanager2.spec
To be able to use fedmsg based umdl runs there needs to be a place to store the last time umdl was run. Using /var/run/mirrormanager in the backend package seems like the right thing to do.
> Also add a /var/run directory for the backend

- utility/mm2_create_install_repo
The wrong version was retrieved from the database and thus the new
repositories were pointing to some bogus version. Now first the
category is retrieved from the database and then with the category
and the product name the correct version is retrieved from the
database.
Additionally the parameter handling was optimized and wrong comments
were removed.
> Fix version handling

- utility/backend_tempfile.conf
So that /var/lock/mirrormanager is created on every reboot it also needs
to be included in tmpfiles.d.
> Do not only create /var/lock/mirrormanager on installation.

- utility/mm2_crawler
The crawler was not able to reach dl.fedoraproject.org due to
firewalls and has therefore disabled the master mirror. Now all
categories which are marked as always up to date count as a
successfully scanned category and are not auto-disabled after a
short time.
> Support always update hosts which are unreachable.

- mirrormanager2/app.py
- mirrormanager2/lib/__init__.py
- mirrormanager2/templates/fedora/index.html
The MM1 publiclist had the possibility to not just sort by
product/version and product/version/arch but also only by product. Now
it is possible to only show EPEL or Fedora mirrors. Necessary for links
which point to only a certain product and are now no longer working.
This solves #75
> Offer possibility to sort by product

- mirrormanager2/app.py
- mirrormanager2/templates/fedora/host.html
- mirrormanager2/templates/fedora/site.html
Fix the label of a submit button from ``Create`` to ``Update`` to reflect what the button does
Only show the ``admin active`` fields to admins
> Couple of UI fixes

- mirrormanager2/lib/model.py
- utility/mm2_update-master-directory-list
I am not sure this 100% correct, but this are the minimal changes to make umdl's delete option work again. Running umdl with --delete in Fedora's MM staging instance reduces the size of a database dump from 800MB to 760MB.
> Umdl delete

- mirrormanager2/app.py
- mirrormanager2/templates/fedora/host_new.html
- mirrormanager2/templates/fedora/site_new.html
Boolean in html are processed in such a way that: present=1 and absent=0
so by hiding the admin_active box to non-admins, we are sending an 'absent'
signal and thus if we do not handle this, we end-up with changing
involuntarily the admin_active flag.
> If the user is not an admin, keep the existing admin_active settings

- utility/mm2_move-to-archive
- utility/mm2_update-master-directory-list
umdl sometimes prints out lines like:
%s: directory already has a repository
this should be fixed and move-to-archive also needed a one line fix.
> Two simple one line fixes.

- utility/mm2_crawler
Currently the crawler cannot be gracefully interrupted. This adds code to (more or less) gracefully shut down the crawler threads once SIGARLM has been received.
> Add support to gracefully shutdown the crawler

- utility/mm2_crawler
With this change a new command-line option is available:
--continent
It can either be used to specify a continent:
--continent AF --continent AS
To only crawl mirrors which (according to GeoIP) are either in Africa
Asia. It can also be used to exclude a continent:
--continent ^EU
Which will scan all mirror which are not in Europe.
The implementation is not optimal which is related to the design of MM.
There is no real location associated with a host. The GeoIP location
can only be done once the categories and the URLs belonging to the
categories are loaded. This means with have to act like we would
actually crawl a host, load the categories and the associated URL.
This implementation now uses the first URL to get (via GeoIP) the
continent this mirror is located. If the mirror is on the …
> Add support to limit crawling by continent

- utility/mm2_update-master-directory-list
This change includes a few smaller fixes to re-enable new repository
detection and creation. The complete fix requires also changes to
repomap.py which will be part of another commit. (#109)
> Fix new repository detection and creation.

- utility/mm2_crawler
Simple fix to not auto-disable hosts if only certain categories are scanned.
> If the host has no categories do not auto-disable it.

- MANIFEST.in
- setup.py
- utility/mirrormanager2.spec
The s3sync scripts wants to run report_mirror. This creates the appropriate package.
> Create client subpackage with report_mirror in it.

- mirrormanager2/lib/__init__.py
Until now get_file_detail() was always used with all optional
parameters specified and thus always the correct FileDetails were
returned. If only the Directory.ID and the name of the file are
specified this function returns the older entry (if multiple entries for
the wanted file exist). This adds an option to reverse the order and so
the newest entry about the given file should be returned.
> Add order option to get_file_detail()

- mirrormanager2/app.py
- utility/mm2_crawler
Some mirrors where failing to be scanned as a leading whitespace broke
our protocol detection (.startswith('rsync')). This ignores whitespace
in the URLs.
> Remove all whitespaces around the mirror URLs

- mirrormanager2/lib/mirrorlist.py
Another try to sort the alternates in the metalink by timestamps in descending order. This time the list is sorted during pkl generation.
https://mirrors.stg.fedoraproject.org/metalink?repo=rawhide&arch=x86_64
Solves #117
> Sort metalinks alternates by timestamps descending

- utility/mm2_crawler
- utility/mm2_propagation
The crawler has been extended to only retrieve the repomd.xml file and print out its sha256sum. To create diagrams of this output an additional script has been added. The script to create the diagrams has a few hard-coded assumptions coded into it which is not perfect but integrating it into mirrormanager2's repository makes sure the script is not lost.
> Add code to graph repomd.xml propagation

- utility/mm2_crawler.logrotate
The per host crawler logs are available via http to be inspected by the
mirror admins if necessary. The current setup to daily rotate those log
files overwrites the log files with (empty) files so fast that most of
the times the log files are empty and have no real value for the mirror
admins. By rotating those log files only once per week the chances are
much higher that they might include useful information.
> Rotate crawler logs once per week

- mirrormanager2/lib/model.py
Deleting a mirror site and/or host did not correctly delete the URLs:
https://github.com/fedora-infra/mirrormanager2/issues/115
https://fedorahosted.org/mirrormanager/ticket/61
As URLs can only exist once in the database the URLs with the deleted
site and/or hosts are still in the database and cannot be added to
another host or deleted. Right now these left-over URLs have to be
deleted manually.
> Deleting URLs if site or host is removed.

- mirrormanager2/app.py
f59f7455 has a bug, setting host.admin_active = True before
form.populate_obj() which immediately sets it to false again
for non-admin users.
Switch those lines.
> Really ensure that new host is admin_active

- utility/mm2_crawler
There was some confusion about the list of files which is checked by the
crawler. The original code was looping over the keys of a dict. Which
seemed to been an unlikely result from a database query. The PR
https://github.com/fedora-infra/mirrormanager2/pull/107
changed it to loop over an existing database query result list.
This change, however, resulted that the crawler was only looking at
repodata directories:
https://github.com/fedora-infra/mirrormanager2/issues/131
The reason the crawler actually has to loop over the keys of a dict is
that umdl reads all the directories and creates a dict of the (maybe 10)
newest files in that directory. This dict is then pickled and stored in
the database and read by the crawler.
Instead of simply reverting the commit which removed the loop over the …
> But it is a dict

- mirrormanager2/default_config.py
- mirrormanager2/forms.py
- utility/mirrormanager2.cfg.sample
This change adds the possibility to exclude certain
protocols to be entered in MirrorManager. The default
value in the configuration file of
MM_PROTOCOL_REGEX = '^(?!ftp)(.*)$'
will prohibit that FTP based URLs are entered at all.
The goal (as discussed in #99) is to remove FTP URLs from Fedora's
MirrorManager setup.
> Optionally exclude certain protocols from MM

- mirrorlist/mirrorlist_server.py
The only use of the '--debug' option was to additionally log the
information for the mirrorlist statistics also to syslog. As the
mirrorlist statistics information is logged to its own file it does not
need to be duplicated to syslog. This completely removes the '--debug'
option.
> mirrorlist: Remove --debug option

- mirrorlist/mirrorlist_server.py
- requirements_mirrorlist.txt
This improves the performance significantly for several reasons:
1. Threading uses a lot less resources than forking in general.
2. Forks have Copy-On-Write for variables. This means that at the
moment of forking, they will just point to the parent process
for all of the memory they stored until now, so they don't have
to actually copy all of the bits of memory over during fork().
The problem here though is at the moment of metalink update:
at this moment, the variables that the master proces uses for
the in-memory structure suddenly all change. This means that
all of the forks that are still active at that time will have
to copy all the previous values to make sure they do not get
impacted by the update. (Linux-specific, I am not sure about
other Operating Systems on this).
One possible …
> Switch the MirrorList server to use threading rather than forking

- mirrorlist/mirrorlist_statistics
- utility/mm2_generate-worldmap
- utility/mm2_propagation
The matplotlib dependent scripts are trying to start a GTK interface if
no configuration file is present (like on my system) which tells that
the non-graphical interface should be used as default. With this it is
not explicitly stated in the code of the scripts that the non-graphical
version is wanted. In addition the dependency to draw the fonts with
Latex has been removed. Also switching to embargoed countries from
configuration file.
> statistics: Fix various matplotlib problems

- mirrormanager2/lib/hostconfig.py
- mirrormanager2/lib/model.py
The field host.config is never used but increases the required memory dramatically for certain database operation. Its loading is now deferred and as it is never read the call write the data has also been removed.
> Defer loading of host.config

- setup.py
- utility/mirrormanager2.spec
- utility/mm2_emergency-expire-repo
I just tried the new emergency script in staging which was introduced with #154.
This PR has a few small fixes to make the script actually run and I also added it to the backend RPM as the script was not installed.
In addition to the described problems it seems not to be doing what it should do. For only one directory the script claims to have changed something:
```
[2016-01-14 08:50:36,228][       mm2    INFO] Clearing for repo pub/fedora/linux/atomic/23
[2016-01-14 08:50:36,236][       mm2    INFO] Files kept: summary
[2016-01-14 08:50:36,236][       mm2    INFO] Older versions deleted: summary
```
Everything else seems unchanged. The metalink output is also the same. The existing alternate entry is not removed. On each run the script produces the same output. …
> Few small fixes to the emergency script

- mirrormanager2/lib/model.py
- utility/mm2_emergency-expire-repo
It was not traversing subdirectories, and as such would not
reach $repo/repodata and the other important directories.
> Finish the emergency cleanup script

- utility/mm2_crawler
This change is required to make the propagation graphing actually work.
It seems this has been fixed manually on the production systems.
> Propagation: Added path to propagation results

- utility/mm2_get_global_netblocks
Fixes #165
The servers providing the IPv4/IPv6 global netblocks do not seem to be
running on UTC and therefore it can happen that when requesting the
netblock list on the first of the month on a UTC system that the
netblock list does not yet exist as the destination server is still in
the previous month. Using yesterday's date should work around/fix this.
> get_global_netblocks: use yesterday's date

- mirrormanager2/lib/umdl.py
As described in
https://fedorahosted.org/fedora-infrastructure/ticket/5185
umdl picks up repositories and versions in the alt/ tree in the staging
directory, which should not be presented on the MirrorManager main page.
umdl already has a check to see if a version is a test version and this
is now extended to also mark releases/repositories/versions in paths
containing 'stage' as 'isTest'.
> umdl: mark paths containing /stage/ also as testing

- mirrorlist/mirrorlist_client.wsgi
- mirrorlist/mirrorlist_server.py
This adds the option specify the desired protocol of the mirrorlist/metalink as described in #100 
The code is currently running in staging and the result can be seen at:
http://mirrors.stg.fedoraproject.org/mirrorlist?repo=rawhide&arch=x86_64&country=jp&protocol=rsync
http://mirrors.stg.fedoraproject.org/mirrorlist?repo=rawhide&arch=x86_64&country=jp&protocol=ftp
http://mirrors.stg.fedoraproject.org/metalink?repo=rawhide&arch=x86_64&country=gb&protocol=https
http://mirrors.stg.fedoraproject.org/metalink?repo=rawhide&arch=x86_64&country=gb&protocol=rsync
> mirrorlist: add protocol option

- client/report_mirror
- mirrormanager2/xmlrpc.py
This means we still allow pickle submissions as a stopgap until we
manage to convince admins to move to json submissions.
Related: CVE-2016-1000003
> Allow submission of checkin information via json

- utility/mm2_crawler
During the crawl of unreadable directories, which can exists in the days
before a release, the crawler tries to count the number of unreadable
directories in the stats dict. The key 'unreadable' does not exist which
means that the crawlers just stops crawling a host once the first
unreadable directory has been found. This means that the crawler will
error out on most hosts just before a release.
> mm2_crawler: Add missing field to stats dict

- mirrorlist/mirrorlist_client.wsgi
The commits
ed7e45903f381a07395b7960a719934414c7c8f5
236532af7a46d50930bdc3f9c8386a063d5960cf
which were used to support the '&protocol=' option broke the mirrorlist
option to answer with a HTTP redirect (302). This fixes the redirect
code path to also work with the new data format returned by the
mirrorlist server.
> mirrolist: fix &redirect=1

- runserver.py
This way the port and host where the application is ran can be set
via the CLI and a config file can be specified to adjust the local
app versus the default config.
> Improve the runserver script

- utility/mm2_crawler
The function which selects the crawl protocol only knows
about 'rsync:', 'http:' and 'ftp:'.
A mirror which only provides 'https' will never be crawled.
This only changes 'http:' to 'http'.
> crawler: also crawl https-only mirrors

- utility/mm2_propagation
The propagation logs contain lot of errors and the script
to parse these logs needs to be more robust to ignore broken lines.
> Make the propagation script more robust

- utility/mm2_move-devel-to-release
mm2_move-devel-to-release was still assuming that the 'releases/'
directory has the 'Everything/' part in it but that 'Everything/' does not
exist under 'development/'. As this has changed this script needs to
adapt to the new layout. Without this change the script was looking for
directories like
pub/fedora-secondary/releases/24/Everything/Everything/ppc64/debug/tree
which do not exist.
Bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1395695
Fixes #195
> mm2_move-devel-to-release: adapt to latest repository layout

- mirrormanager2/app.py
- mirrormanager2/templates/fedora/host_category.html
- mirrormanager2/templates/fedora/host_category_url_new.html
MirrorManager has the concept of private URLs which should be used
for inter-mirror syncing. Unfortunately they are sometimes confused
with the concept of private mirrors. Private URLs will never show up in
the mirrorlist/metalink and if a private mirror (only for a certain
network or host) marks a URL as private it will not show up.
As the private flag is not reflected anywhere on the web pages it can
only be seen in the database.
With this change a private URL is now also displayed as private in the
host category URL view and only admins can mark URLs as private.
> Private URLs are now restricted to admins

- mirrorlist/mirrorlist_server.py
If less than three mirrors for a country/continent are found the
mirrorlist is extended by the global mirrorlist. This increases the
value from three to five as there have been problems especially with
countries/continents with a low number of mirrors (Australia).
In addition the minimum number of mirrors threshold can now be specified
on the command-line: -m, --minimum
Important to know is that if a specific country is requested from the
mirrorlist using '&country=AU' described mechanism does not take effect,
only for regular requests (without country) or requests for a specific
IP ('&ip=xxx.xxx.xxx.xxx').
> mirrorlist: at least 5 mirrors should be returned for country/continent

- mirrormanager2/default_config.py
- mirrormanager2/templates/fedora/host.html
- mirrormanager2/templates/fedora/host_acl_ip_new.html
- utility/mirrormanager2.cfg.sample
This adds a configuration option to enable/disable the 'Master rsync
server Access Control List IPs' section in the host template. As Fedora
has never (or at least for a long time not) used this functionality this
disables if by default in the Fedora templates.
It could have been completely removed from the Fedora templates, but as
long as the Fedora templates are the only templates I just conditionally
disabled it.
> Remove 'Master rsync server Access Control List IPs' section

- utility/mirrormanager2.spec
Signed-off-by: Patrick Uiterwijk puiterwijk@redhat.com
> Remove <0.80 requirement on IPy

- utility/mm2_crawler.logrotate
compress crawler logs, save us some space on the crawler machines. 🐄
> compress crawler logs in logrotate. They are small, but they add up

- mirrorlist/mirrorlist_client.wsgi
- mirrorlist/mirrorlist_server.py
- mirrormanager2/lib/mirrorlist.py
When the mirrorlist_server.py process is 'kill -1'-ed to reload its
data, the new data is sometimes not reloaded. Once the mirrorlist
process is in such a state only a complete restart seems to help.
This adds an additional GET parameter to query the database generation
time:
$ curl 'http://localhost/mirrorlist?repo=epel-7&arch=x86_64&country=global&time'
> mirrorlist: add pkl generation time to pkl

- mirrormanager2/app.py
- mirrormanager2/default_config.py
- mirrormanager2/forms.py
- utility/mirrormanager2.cfg.sample
Backport from mirrormanager1:
https://pagure.io/mirrormanager/blob/master/f/server/mirrormanager/controllers.py#_655
The original mirrormanager implementation restricted IPv4 netblock sizes
to /16 and IPv6 netblock sizes to /32. This is used to prevent mirror
admins to make the whole internet their local netblock.
This change reintroduces the above code from the original mirrormanager
implementation.
> restrict non-admin users to certain netblock sizes

- README.rst
- doc/contributing.rst
- doc/development.rst
- doc/index.rst
- mirrorlist/mirrorlist_server.py
- mirrormanager2/templates/fedora/admin/admin_master.html
- mirrormanager2/templates/fedora/master_noauth.html
- setup.py
- utility/mirrormanager2.spec
- utility/mm2_crawler
Note that we will have to change this all again when we move to pagure.
> Change all references from fedorahosted.org to use the github area.

- mirrormanager2/lib/umdl.py
- utility/mm2_update-master-directory-list
Disk based scanning all modules of the Fedora master mirror takes hours.
A full scan takes (at least) more than 6 hours and stat()s every
directory in the whole tree. This creates a massive amount of IOPS which
are basically only used to detect that most directories have not
changed.
With the newly created fullfiletimelist-* files for fedora-quick-mirror
(https://pagure.io/quick-fedora-mirror/) this can be changed and a nearly
stat()-less master mirror scan is possible and implemented by this commit.
Important to remember is that the result will always only be as good as
the input files (fullfiletimelist-*).
With this commit umdl detects if a 'fullfiletimelist-*' file exists and
instead of walking the directory tree only the found file is parsed. To
switch back to disk based scanning a …
>  umdl: add fullfiletimelist-* based master scanning

- mirrorlist/mirrorlist_server.py
This reverts a small part of dad4e76899b28755c39d4f494f618a5a4037ebf7.
Changing the XML namespace needs to be more coordinated.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
> Revert namespace change - this breaks namespace aware xml parsers

- mirrormanager2/lib/repomap.py
in the new Modular world we need to setup a new structure for
delivering content. it will look something like bellow
/pub/fedora/linux/modular/
/pub/fedora/linux/modular/development
/pub/fedora/linux/modular/development/bikeshed
/pub/fedora/linux/modular/development/27
/pub/fedora/linux/modular/releases
/pub/fedora/linux/modular/releases/test
/pub/fedora/linux/modular/updates
/pub/fedora/linux/modular/updates/27
/pub/fedora/linux/modular/updates/testing
/pub/fedora/linux/modular/updates/testing/27
under each releasever 27, 28 bikeshed etc will be a directory for
the consumable product Server, Workstation, Atomic, etc. For each
consumable product we will have to setup a new set of prefixes. We
are starting with Server.
Signed-off-by: Dennis Gilmore <dennis@ausil.us>
> detect and setup mirrorlist/metalinks for modular Fedora

- utility/mm2_update-master-directory-list
This is a fix for
https://pagure.io/fedora-infrastructure/issue/6286
This hardcodes a list ('Cloud', 'Server', 'Workstation') to skip before
creating a repository. This should leave 'Everything' and other strings,
like used in the updates directory structure.
Not totally sure of the side effects of this change.
> umdl: only create repositories for 'Everything'

- mirrormanager2/lib/repomap.py
- utility/mm2_update-master-directory-list
The 'modular' repository detection from PR #220 needed some fixes.
The repository detection was not entirely correct (some ifs at the wrong
level) and a newly merged feature to not create repositories for
('Cloud', 'Server', 'Workstation') blocked the creation of the modular
Server repository (PR #219).
> umdl: fix 'modular' repository detection

- mirrormanager2/app.py
- mirrormanager2/lib/__init__.py
The original MirrorManager code base had the feature to hide certain
arches and products from the publiclist. The database fields still exist
and are even set to 'false' for certain arches.
There is the ticket https://pagure.io/fedora-infrastructure/issue/5186
which tried to remove unused architectures from the publiclist
(sparc and sparc64). Using the now unused database column 'publiclist'
seems like the right thing to do to hide certain arches (including
source) from the publiclist. RPM Fusion which still uses the original
MirrorManager code base is a good example how it used to look:
http://mirrors.rpmfusion.org/mm/publiclist/
The architecture 'source' is not displayed, which has in both instances
(Fedora and RPM Fusion) publiclist = False. It still can be seen in
Fedora: …
> publiclist: hide disabled arches and products

- mirrormanager2/lib/repomap.py
To make umdl detect the modular updates repositories the repomap prefix
detection had to be moved under isModular. Now some update repositories
are under isUpdates* and some are under isModular.
repomap.py has become unreadable and should actually be a
configuration file, somehow.
> repomap: fix modular updates repository

- .travis.yml
Use containers to test MirrorManager2 in centos:7, fedora:latest and
fedora:rawhide
> travis: added .travis.yml for automatic testing

- mirrormanager2/admin.py
- mirrormanager2/app.py
- mirrormanager2/forms.py
- mirrormanager2/login.py
- mirrormanager2/login_forms.py
- tests/__init__.py
Running the test cases on Fedora showed a few flask.ext deprecation
warnings. With this commit those are fixed by using flask_admin or
flask_wtf. Even if RHEL/CentOS does not show the deprecation warnings
the newer names also work there.
> fix flask.ext deprecation warnings

- tests/test_ui_app.py
After adding the reactivated test cases to the spec file a few network
dependent (id.fedoraproject.org) test cases started to fail. This skips
those tests if MM2_SKIP_NETWORK_TESTS=1.
> tests: add possibility to skip network

- mirrormanager2/lib/sync.py
- tests/test_crawler.py
- utility/mm2_crawler
Over two years ago PR #134 added support to abort the rsync based crawls if it takes too long. This commit now uses this existing timeout support to the crawler. The timeout is set to 90% of the remaining crawl time for the current host. This is also related to #77.
> crawler: use timeout also on rsync crawls

- .travis.yml
- tests/setup_test_container.sh
- tests/test_crawler.py
The container setup to run the tests on centos-7 fedora-rawhide and
fedora-latest was using yum to install the packages on all systems as
that made it possible to install all three test scenarios with one
command. This no longer works as rich dependencies are not resolved by
yum and thus the test environment could no longer be correctly set up.
This commit introduces a shell script to set up the container based on
the ${DISTRO}.
Another change is to decrease the timeout for the timeout run_rsync test
case.
> tests: fix broken test results

- utility/mm2_get_internet2_netblocks
mm2_get_internet2_netblocks used to use
http://zebra.net.internet2.edu/bgp/ to download routing information. As
the provider of that routing information changed their system the URL no
longer existed (see #226).
After opening a ticket at https://routerproxy.grnoc.iu.edu/internet2/ I
was told that they simply forgot about it and they are now providing
similar data at: https://routes.net.internet2.edu/bgp/
This updates the mm2_get_internet2_netblocks script to use the new
location and to handle the data from the new location correctly.
> Make mm2_get_internet2_netblocks work again

- utility/mm2_crawler
Until now mirrormanager supported HTTPS only sites but implicitly
expected that the same URL as the HTTPS URL is also available via HTTP.
And although the mirror is using a HTTPS URL mirrormanager actually used
HTTP to scan the mirror.
This change adds HTTPS support at a few places so that HTTPS only
mirrors are also supported.
> crawler: support https only hosts

- mirrormanager2/forms.py
- mirrormanager2/templates/fedora/my_sites.html
The terms "site" and "host" have a special meaning in MirrorManager. One
'Site' can consist of multiple 'Host's but the terms were not used
consistently. This tries to address that by renaming 'Site name' in the
host to 'Host name' and by renaming 'Mirror' to 'Hosts' when showing the
overview.
> Use "site", "host" and "mirror" consistently

- mirrormanager2/lib/repomap.py
- utility/mm2_update-master-directory-list
This is based on Dennis' PR #237 to support the new location of the
'modular' content. This moves the original code a bit around to work
correctly. This has been tested in staging and repositories have been
created correctly:
```
prefix
------------------------
rawhide-modular
rawhide-modular
rawhide-modular
rawhide-modular-source
rawhide-modular-debug
rawhide-modular-debug
rawhide-modular-debug
```
Additional, now unnecessary, 'modular' handling code has been removed
from umdl.
> repomap: modular changes for Fedora 28

- utility/mm2_crawler
The calculation for the rsync timeout was completely wrong. Instead of
calculating the remaining time for the current crawler thread the time
the thread was running was calculated. Which was most of the time 1
second for the first crawled category. This lead to rsync being aborted
after 1 second and the crawler switched to http(s).
With this the remaining time of the crawler thread is now calculated
correctly.
> crawler: Correctly calculate the remaining time

- mirrormanager2/lib/repomap.py
The whole repomap logic is much too complicated and this might have
already existing in some previous versions of repomap.py.
This change has already been verified in Fedora's production
MirrorManager instance.
> repomap: more modular repository detection logic

- utility/mm2_crawler
PR #240 added support to actually scan HTTPS URLs with HTTPS instead of
always using HTTP for HTTPS (really!). The changes from PR #240, however,
let to errors in the keep-alive handling of MirrorManager.
MirrorManager tries to keep connections open if the remote side supports
keep-alive and reuses that connection on subsequent requests.
MirrorManager, however, does not actively track if the keep-alive
connection has been closed by the remote side. If a request fails
MirrorManager does single retry before returning a failure.
For HTTP connections the try/except block seems to be different than for
HTTPS connections.
This adds the code which fails during remotely closed keep-alive
HTTPS connections to the try/except block which seemed to be enough for
HTTP connections.
See: …
> crawler: correctly handle keep-alive for HTTPS

- utility/mm2_crawler
In one last place (hopefully) the crawler was not yet category based
crawling aware. Instead of removing the not up to date directories from
the current category it removed the directories from all existing host
categories. The means that whenever one category is scanned, all other
categories are automatically empty.
Instead of looking at all categories of a host the crawler now only
looks at those categories specified on the command-line.
> crawler: only update directories of the current category

- mirrormanager2/lib/umdl.py
- utility/mirrormanager2.spec
- utility/mm2_umdl2
- utility/mm2_update-master-directory-list
- utility/mm2_update-single-file-detail
With the coming deprecation of yum in Fedora this changes MirrorManager
to use rpmmd instead of yum to read the repomd.xml files.
Fixes: #251
> rpmmd: switch from yum.repoMDObject pyrpmmd

- mirrormanager2/forms.py
- mirrormanager2/login_forms.py
The documentation of wtforms says that Required() is deprecated and that
either DataRequired or InputRequired() should be used for the
validators. This switches all uses of Required() to InputRequired()
which also fixes two broken test cases.
> Use InputRequired() instead of Required()

- utility/mm2_crawler
When using the crawler to scan each category separately a non-existing
category resets the failure counter to 0. This way almost no mirror will
ever be auto-disabled (except broken mirrors having all categories configured).
> crawler: correctly auto-disable mirrors

- client/report_mirror
- mirrormanager2/lib/hostconfig.py
- mirrormanager2/xml_rpc.py
This tries to fix https://bugzilla.redhat.com/show_bug.cgi?id=1707684 which reported that report_mirror does not work. This now works with python2 and python3.
At the same time this adds some debug output to the xmlrpc checkin code. to better see which hosts are using pickle and which are using json.
> Fix report_mirror with python3

- README.rst
- mirrorlist/mirrorlist_server.py
- mirrorlist/test/server_tester.py
- mirrorlist/weighted_shuffle.py
- mirrormanager.proto
- mirrormanager2/lib/mirrorlist.py
- requirements.txt
- requirements_mirrorlist.txt
- runtests.sh
- tests/__init__.py
- tests/setup_test_container.sh
- tests/test_crawler.py
- tests/test_mdtr.py
- tests/test_mm_lib_model.py
- tests/test_mmlib.py
- tests/test_mta.py
- tests/test_ui_admin.py
- tests/test_ui_app.py
- tests/test_umdl.py
- utility/mirrormanager2.spec
- utility/mm2_crawler
This is an experiment to see if protbuf is better suited for data transfer from the backend to the mirrorlist server.
> Use protobuf instead of pickle for backend - mirrorlist data exchange

- mirrormanager2/lib/repomap.py
This lets mirrormanager detect the newly added playground repositories.
> repomap: add playground support

- mirrormanager2/templates/fedora/master_noauth.html
Fixes #271 "Remove fedmenu from mirrormanager2"
From looking at the revision history, it is my understanding that fedmenu brought in a dependency to jQuery 1.11.2 with it as can be seen in 888245cc76ad5c44f969459b0747acafb3bbfc07.
I wasn't sure I could remove the reference to it since bootstrap takes a dependency on jQuery and I don't know if it takes care of bringing it in itself.
> Removes fedmenu from mirrormanager2

- mirrormanager2/lib/mirrorlist.py
- utility/mm2_update-mirrorlist-server
If the mirrorlist data exporter is writing pkl and protobuf files at the
same time some database queries are running twice, which can take a lot
of time. This change moves all database queries in the
populate_all_caches() function which is the correct place. Previously
some queries were run in populate_all_caches() and some in
dump_ccaches().
This commit also includes a single line change to
mm2_update-mirrorlist-server to forward all parameters to the actual
data exporter script.
> Only query database once for mirrorlist export

- mirrormanager2/app.py
- tests/test_ui_app.py
Without this change it was possible to manually inspect other Hosts and Sites by replacing the Site-ID or Host-ID with another ID. This adds the necessary checks to all Site and Host related actions.
Broken tests have been fixed and extended.
> Disallow users accessing other hosts and sites

- mirrormanager2/default_config.py
- mirrormanager2/lib/umdl.py
- utility/mirrormanager2.cfg.sample
- utility/mm2_update-master-directory-list
UMDL sometimes creates version entries in the database in locations which do not actually carry are release/version. In Fedora this happens most of the time with pub/alt. This adds a configuration variable which tells umdl to skip these directories.
Fixes: #263
> umdl: skip certain paths for version detection

- mirrormanager2/forms.py
- mirrormanager2/login_forms.py
This fixes:
DeprecationWarning: The TextField alias for StringField has been deprecated and will be removed in WTForms 3.0
> Fix WTForms deprecation warnings

- mirrormanager2/lib/hostconfig.py
One of the limitations of the current report_mirror implementation is that it only transmits a list of directories to MirrorManager. That works most of the times, but a common error scenario we are seeing is that the crawler detects that a mirror is out of sync but report_mirror is still running. This leads to the situation that correctly deactivated mirrors by the crawler are enabled again. This is one of the most common problems we are seeing in Fedora with mirrors.
For private mirrors we still need report_mirror, but for public mirror this commit turns the report_mirror interface off.
> Disable report_mirror for public mirrors

- mirrormanager2/lib/repomap.py
- mirrormanager2/lib/umdl.py
This adds fedora-cisco-openh264-* repository detection to repomap.py and adapts _get_version_from_path() to correctly detect versions in the openh264 tree.
The 'fix' for the version detection is a revert of the followingoriginal MirrorManager code:
```
commit 131d6ee4e5870de467ccef5bf60108e7641caace
Author: Adrian Reber <adrian@lisas.de>
Date:   Tue Nov 16 07:00:41 2010 -0600
umdl: handle CentOS
```
> Add support to handle fedora-cisco-openh264-*

- .travis.yml
- mirrormanager2/app.py
- mirrormanager2/default_config.py
- mirrormanager2/forms.py
- tests/__init__.py
- tests/setup_test_container.sh
- tests/test_ui_app.py
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>
> Change the way the FPCA is checked

- mirrormanager2/lib/migrations/versions/e67aacbf9f4f_host_geo_coordinates.py
- mirrormanager2/lib/model.py
- mirrormanager2/static/fedora/mirrormanager2.css
- mirrormanager2/templates/fedora/_macros.html
- mirrormanager2/templates/fedora/mirrors_location.txt
- mirrormanager2/utility/generate_worldmap.py
- mirrormanager2/views.py
> Store the mirror geolocation in the DB

- mirrormanager2/views.py
- tests/test_ui_app.py
previously, if a user tried to create a category URL that already existed in a category, it was caught as a SQLALCHEMY integrity error, and the application did not crash. However we just printed the exception to the logs, and it looked like an error. This commit adds some error checking to see if the URL already exitst, and informs the user as such.
Resolves: #317
> Add specific check for duplicate cat URLS

- mirrormanager2/crawler/cli.py
- mirrormanager2/crawler/notif.py
- mirrormanager2/lib/notifications.py
- mirrormanager2/views.py
- poetry.lock
- pyproject.toml
Use the message schemas provided by `mirrormanager-messages`. The changes to `crawler/notif.py` aren't tested, but we don't emit Fedora Messaging messages from the crawler at the moment.
Fix: #353
> Use the message schemas

- mirrormanager2/crawler/continents.py
- mirrormanager2/lib/geo.py
- mirrormanager2/utility/generate_worldmap.py
socket.gethostbyname only returns a single IPv4 address. Any additional
IPv4 addresses and all IPv6 addresses are ignored. As a consequence,
hosts without IPv4 addresses are ignored and any additional information
from additional IPv4 addresses is ignored. If IPv4 addresses are rotated
by the implementation of socket.gethostbyname, for example, common with
DNS servers and resolvers, the geolocation information for the host can
change without every call of socket.gethostbyname.
It seems better to consider all addresses, both all IPv4 and IPv6
addresses, and to summarize the geolocation information when only a
single result is required.
> Use socket.getaddrinfo instead of socket.gethostbyname

- mirrormanager2/forms.py
- poetry.lock
- pyproject.toml
- utility/mirrormanager2.spec
The Python standary library includes ipaddress packages since Python 3.3. Therefore, the IPy can be replaced
> Replace IPy with ipaddress

- poetry.lock
- pyproject.toml
Python 2 is no longer supported for mirrormanager2. Therefore, the dependency to six can be removed.
> Remove six dependency

- mirrormanager2/crawler/ftp_connector.py
- mirrormanager2/crawler/http_connector.py
- mirrormanager2/crawler/rsync_connector.py
- mirrormanager2/lib/__init__.py
- tests/test_crawler.py
> Crawler: consider empty directories as up-to-date
